version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
      - ./backend/cspm.db:/app/cspm.db
  frontend:
    build:
      context: ./frontend
    command: ["npm","run","dev","--","--host"]
    ports:
      - "5173:5173"
    environment:
      - VITE_API=http://backend:8000
    depends_on:
      - backend
